### ISSUE TITLE
Vitest-like Mocking: Feature tracking

### ISSUE THREAD

**Issue by goosewobbler** [webdriverio-community/wdio-electron-service#368]
Some of the below are vitest features (we are wrapping `@vitest/spy`) which simply need documenting.

- [x] Mock Object
  - [x] [`mockImplementation`](https://vitest.dev/api/mock.html#mockimplementation)
  - [x] [`mockImplementationOnce`](https://vitest.dev/api/mock.html#mockimplementationonce)
  - [x] [`mockReturnValue`](https://vitest.dev/api/mock.html#mockreturnvalue)
  - [x] [`mockReturnValueOnce`](https://vitest.dev/api/mock.html#mockreturnvalueonce)
  - [x] [`mockRestore`](https://vitest.dev/api/mock.html#mockrestore)
  - [x] [`mockReset`](https://vitest.dev/api/mock.html#mockreset)
  - [x] [`mockClear`](https://vitest.dev/api/mock.html#mockclear)
  - [x] [`mockResolvedValue`](https://vitest.dev/api/mock.html#mockresolvedvalue)
  - [x] [`mockResolvedValueOnce`](https://vitest.dev/api/mock.html#mockresolvedvalueonce)
  - [x] [`mockRejectedValue`](https://vitest.dev/api/mock.html#mockrejectedvalue)
  - [x] [`mockRejectedValueOnce`](https://vitest.dev/api/mock.html#mockrejectedvalueonce)
  - [x] [`withImplementation`](https://vitest.dev/api/mock.html#withimplementation)
  - [x] [`getMockImplementation`](https://vitest.dev/api/mock.html#getmockimplementation)
  - [x] [`getMockName`](https://vitest.dev/api/mock.html#getmockname)
  - [x] [`mockName`](https://vitest.dev/api/mock.html#mockname)
  - [x] [`mockReturnThis`](https://vitest.dev/api/mock.html#mockreturnthis)
  - [x] [`mock.calls`](https://vitest.dev/api/mock.html#mock-calls)
  - [x] [`mock.lastCall`](https://vitest.dev/api/mock.html#mock-lastcall)
  - [x] [`mock.results`](https://vitest.dev/api/mock.html#mock-results)
  - [x] [`mock.invocationCallOrder`](https://vitest.dev/api/mock.html#mock-invocationcallorder)
- [x] Utilities
  - [x] [`isMockFunction`](https://vitest.dev/api/vi.html#vi-ismockfunction)
  - [x] [`clearAllMocks`](https://vitest.dev/api/vi.html#vi-clearallmocks)
  - [x] [`resetAllMocks`](https://vitest.dev/api/vi.html#vi-resetallmocks)
  - [x] [`restoreAllMocks`](https://vitest.dev/api/vi.html#vi-restoreallmocks)
- [x] Config Options
  - [x] [`clearMocks`](https://vitest.dev/config/#clearmocks)
  - [x] [`resetMocks`](https://vitest.dev/config/#mockreset)
  - [x] [`restoreMocks`](https://vitest.dev/config/#restoremocks)
